build:
  environment:
    php: '7.4'
  tests:
    override:
      command: "php -v" # Disable tests for Scrutinizer as they're handled by Github Actions

checks:
    php:
        simplify_boolean_return: true
        return_doc_comment_if_not_inferrable: true
        properties_in_camelcaps: true
        parameters_in_camelcaps: true
        param_doc_comment_if_not_inferrable: true
        more_specific_types_in_doc_comments: true
        fix_use_statements:
            remove_unused: true
        fix_line_ending: true
        check_method_contracts:
            verify_interface_like_constraints: true
            verify_documented_constraints: true
            verify_parent_constraints: true

coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
