# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    default_addr: '127.0.0.1:3000'
    default_transport_url: 'php://localhost?size=1000'
    default_jwt_algorithm: 'HS256'
    addr: '%env(default:default_addr:string:ADDR)%'
    transport_url: '%env(default::string:TRANSPORT_URL)%'
    storage_url: '%env(default::string:STORAGE_URL)%'
    metrics_url: '%env(default::string:METRICS_URL)%'
    cors_allowed_origins: '%env(default::string:CORS_ALLOWED_ORIGINS)%'
    publish_allowed_origins: '%env(default::string:PUBLISH_ALLOWED_ORIGINS)%'
    jwt_key: '%env(default::string:JWT_KEY)%'
    jwt_algorithm: '%env(default:default_jwt_algorithm:string:JWT_ALGORITHM)%'
    publisher_jwt_key: '%env(default::string:PUBLISHER_JWT_KEY)%'
    publisher_jwt_algorithm: '%env(default::string:PUBLISHER_JWT_ALGORITHM)%'
    subscriber_jwt_key: '%env(default::string:SUBSCRIBER_JWT_KEY)%'
    subscriber_jwt_algorithm: '%env(default::string:SUBSCRIBER_JWT_ALGORITHM)%'
    allow_anonymous: '%env(bool:ALLOW_ANONYMOUS)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    BenTools\MercurePHP\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'
            - '../src/functions.php'
