name: CI Workflow

env:
  CODECOV_TOKEN: "bfaef100-626e-4f5a-827d-8e6d629f8388"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Redis Server in GitHub Actions
      uses: supercharge/redis-github-action@1.1.0

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Enable Composer parallel downloads
      run: composer global require symfony/flex

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run unit tests
      run: composer tests:unit:run:with-coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.0.7

    - name: Run integration tests with default transport (PHP)
      run: composer tests:integration:run
      env:
        TRANSPORT_URL: php://localhost?size=1000

    - name: Run integration tests with Redis transport
      run: composer tests:integration:run
      env:
        TRANSPORT_URL: redis://localhost

    - name: Check code style
      run: composer phpcs:check

    - name: Track avoidable bugs
      run: composer phpstan:analyze
